### ISSUE TITLE
YCCK/CMYK images cause an error + a tiny bug in cnn_imagenet_init.m

### ISSUE THREAD

**Issue by okvol** [vlfeat/matconvnet#360] opened 2015-12-27 09:09 UTC
line 78:

  if size(imt,3) == 1
    imt = cat(3, imt, imt, imt) ;
  elseif size(imt,3) == 4 %  sometimes the image can be a * b * 4, which will crash the training. I added this condition to correct this.
      imt = imt(:,:,1:3); 
  end

**Comment by okvol** [comment] 2015-12-27 11:14
Another tiny bug:
In cnn_imagenet_init.m
All the "bn%d" should be replaced by "bn%s" since you use string as the argument.

**Comment by lenck** [comment] 2015-12-28 17:30
Hi, fixed the `bn%d` bug. Thanks for reporting it! :)
But in which cases do the images have 4 channels? This seems more like an adjustment to some special data with an alpha channel which are not present in ILSVRC12?

**Comment by okvol** [comment] 2015-12-29 20:46
I do use ILSVRC12. Not sure why I got 4 channels. But there are several of them in the entire datatset.

**Comment by AruniRC** [comment] 2015-12-30 15:48
Hi, there are about 20 4-channel CMYK images in ILSVRC12 dataset.


Aruni Roy Chowdhury
http://people.cs.umass.edu/~arunirc/

**Comment by lenck** [comment] 2015-12-30 16:57
@AruniRC Hmm, it seems that the CMYK support is nevertheless broken in `vl_imreadjpeg`. Funny enough, Matlab's `imread` does not support CMYK images either...

**Comment by lenck** [comment] 2015-12-30 18:47
Ugh, at least in the `libjpeg` and the YCCK colour format it may not be a [trivial task](http://sourceforge.net/p/libjpeg-turbo/patches/15/) :(
I've patched the master branch so that it fails in case when the requested conversion to RGB is ignored. So, instead of failing on the affected line it fails when it will try to use `imread`. Improvement ;)
Also, do you know which images from ILSVRC are in the CMYK format? Just googling I was able to find only some YCCK, but not CMYK images...

**Comment by AruniRC** [comment] 2016-01-01 03:40
Hi @lenck, here's the list of files attached.
I tried several MATLAB workarounds for the conversion, but none of them produced proper images.

Finally I think we just used some external tool to manually convert these 23 images into 3 channel RGB.

[filenames.txt](https://github.com/vlfeat/matconvnet/files/75848/filenames.txt)

**Comment by lenck** [comment] 2016-01-04 12:44
Hmm, my mistakes because there seems to be a duplicate of this issue #91 ... And now I'm not sure if I haven't made it worse with my patch :)
@AruniRC Thanks for the list! It's will be useful as a test case!

**Closed** 2016-01-11 10:40 UTC
Labels: bug
