### ISSUE TITLE
Does we have any function to realize weight sharing?

### ISSUE THREAD

**Issue by llyydd007** [vlfeat/matconvnet#114] opened 2015-04-06 12:09 UTC
Hello,everyone. Does matconvnet has any  ways to realize weight sharing? Thanks very much!

**Comment by vedaldi** [comment] 2015-04-06 12:38
Hi, it is not implemented directly, but it can be done by designing a new wrapper or modifying the existing one. However, it is likely that we will add this functionality in the future.

**Comment by llyydd007** [comment] 2015-04-07 06:21
Ok, thank you. I am looking forward for it. Best wishes.

**Comment by lenck** [comment] 2015-04-14 14:23
Hi, sorry for late response, but if I understand you correctly that should be fine :) Only thing is that in the mex files, the weights are not changed at all - so basically what you need to rewrite is only the part of `cnn_train` where you update weights (e.g. take the average over the groups' dzdw and apply to the group filters, so all the groups are equal).

**Comment by llyydd007** [comment] 2015-04-29 04:59
Thank you @lenck . I finally just not average over the groups' dzdw but use the the groups' dzdw sequentially  to update the groups filter, It seems to go well and It seems to be equal with sum the gradients without averaging. I will try to average it to make a comparison  later.

**Comment by eunjoa** [comment] 2015-11-06 07:24
Hello, i am wondering what do you mean by parameter sharing is not implemented directly ? it seems to me that the convolution layers implementation assume the parameter sharing which means every feature map learns the same set of filter. thank you

**Comment by lenck** [comment] 2016-04-15 10:58
Hi, weight sharing is now easy to achieve with the DaG wrapper (simply by naming providing two conv layers the same name of the parameters). I hope it is fine that I will close this issue then.

**Closed by lenck** 2016-04-15 10:58 UTC

**Comment by yushuinanrong** [comment] 2016-09-30 17:51
@lenck 
Hi Lenck,

Is it possible to share a ratio of weights at each conv layers in MatConvNet?

Thanks
